# Generated by Django 3.0.8 on 2020-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default='Defualt Value'),
        ),
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='destination_4.jpg', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
