# Generated by Django 3.0.8 on 2020-08-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0002_auto_20200801_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('coupon', models.CharField(max_length=100)),
            ],
        ),
    ]
