# Generated by Django 3.0.8 on 2020-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0003_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='coupon',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
