# Generated by Django 3.0.8 on 2020-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socius', '0004_auto_20200807_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
